name: Test CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: SetUp Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./proybackendgrupo08
          file: ./proybackendgrupo08/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: SetUp Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./proyfrontendgrupo08
          file: ./proyfrontendgrupo08/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
