name: Test CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy-backend:
    name: build backend && push image to docker hub
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
        
      - name: docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: build and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./proybackendgrupo08
          file: ./proybackendgrupo08/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
  
  deploy-frontend:
    name: build frontend && push image to docker hub
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
        
      - name: docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./proyfrontendgrupo08
          file: ./proyfrontendgrupo08/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
